[napcat_server] # Napcat连接的ws服务设置
host = "ws://localhost/ws"      # Napcat设定的主机地址，请把"localhost"替换为实际ip地址
port = 8099             # Napcat设定的端口 

[chat] # 群聊白名单功能
group_list = [] # 白名单，请添加您的群组ID
# 只有白名单中的群组可以聊天